"""Initial migration

Revision ID: 0b0ede936a42
Revises:
Create Date: 2026-03-29 23:08:36.482819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "0b0ede936a42"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memories_id"), table_name="memories")
    op.drop_table("memories")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_login_attempts_id"), table_name="login_attempts")
    op.drop_index(
        op.f("ix_login_attempts_username_or_email"), table_name="login_attempts"
    )
    op.drop_table("login_attempts")
    op.drop_index(
        op.f("ix_robot_market_comments_id"), table_name="robot_market_comments"
    )
    op.drop_table("robot_market_comments")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(
        op.f("ix_robot_market_favorites_id"), table_name="robot_market_favorites"
    )
    op.drop_table("robot_market_favorites")
    op.drop_table("task_demonstrations")
    op.drop_index(
        op.f("ix_robot_market_listings_id"), table_name="robot_market_listings"
    )
    op.drop_table("robot_market_listings")
    op.drop_index(
        op.f("ix_password_reset_tokens_id"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_camera_frames_id"), table_name="camera_frames")
    op.drop_table("camera_frames")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_demonstration_frames_id"), table_name="demonstration_frames")
    op.drop_table("demonstration_frames")
    op.drop_index(
        op.f("ix_knowledge_search_history_id"), table_name="knowledge_search_history"
    )
    op.drop_table("knowledge_search_history")
    op.drop_index(op.f("ix_memory_associations_id"), table_name="memory_associations")
    op.drop_table("memory_associations")
    op.drop_index(op.f("ix_training_results_id"), table_name="training_results")
    op.drop_table("training_results")
    op.drop_index(op.f("ix_twofa_temp_sessions_id"), table_name="twofa_temp_sessions")
    op.drop_index(
        op.f("ix_twofa_temp_sessions_temp_token"), table_name="twofa_temp_sessions"
    )
    op.drop_table("twofa_temp_sessions")
    op.drop_index(op.f("idx_downloads_created_at"), table_name="robot_market_downloads")
    op.drop_index(
        op.f("idx_downloads_listing_user"), table_name="robot_market_downloads"
    )
    op.drop_index(
        op.f("ix_robot_market_downloads_id"), table_name="robot_market_downloads"
    )
    op.drop_table("robot_market_downloads")
    op.drop_index(op.f("ix_agi_models_id"), table_name="agi_models")
    op.drop_table("agi_models")
    op.drop_index(op.f("ix_demonstrations_id"), table_name="demonstrations")
    op.drop_table("demonstrations")
    op.drop_index(op.f("ix_robot_market_ratings_id"), table_name="robot_market_ratings")
    op.drop_table("robot_market_ratings")
    op.drop_index(op.f("ix_email_2fa_codes_id"), table_name="email_2fa_codes")
    op.drop_table("email_2fa_codes")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_demonstration_tasks_id"), table_name="demonstration_tasks")
    op.drop_table("demonstration_tasks")
    op.drop_index(
        op.f("ix_email_verification_tokens_id"), table_name="email_verification_tokens"
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_token"),
        table_name="email_verification_tokens",
    )
    op.drop_table("email_verification_tokens")
    op.drop_index(op.f("ix_robots_id"), table_name="robots")
    op.drop_table("robots")
    op.drop_index(op.f("ix_chat_sessions_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_robot_sensors_id"), table_name="robot_sensors")
    op.drop_table("robot_sensors")
    op.drop_index(op.f("ix_knowledge_items_id"), table_name="knowledge_items")
    op.drop_table("knowledge_items")
    op.drop_index(op.f("ix_robot_joints_id"), table_name="robot_joints")
    op.drop_table("robot_joints")
    op.drop_index(op.f("ix_training_jobs_id"), table_name="training_jobs")
    op.drop_table("training_jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_jobs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=True),
        sa.Column("progress", sa.FLOAT(), nullable=True),
        sa.Column("config", sa.TEXT(), nullable=True),
        sa.Column("result", sa.TEXT(), nullable=True),
        sa.Column("started_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["agi_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_training_jobs_id"), "training_jobs", ["id"], unique=False)
    op.create_table(
        "robot_joints",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("robot_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("joint_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("min_position", sa.FLOAT(), nullable=True),
        sa.Column("max_position", sa.FLOAT(), nullable=True),
        sa.Column("max_velocity", sa.FLOAT(), nullable=True),
        sa.Column("max_torque", sa.FLOAT(), nullable=True),
        sa.Column("offset", sa.FLOAT(), nullable=True),
        sa.Column("direction", sa.FLOAT(), nullable=True),
        sa.Column("current_position", sa.FLOAT(), nullable=True),
        sa.Column("current_velocity", sa.FLOAT(), nullable=True),
        sa.Column("current_torque", sa.FLOAT(), nullable=True),
        sa.Column("temperature", sa.FLOAT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("parent_link", sa.VARCHAR(length=100), nullable=True),
        sa.Column("child_link", sa.VARCHAR(length=100), nullable=True),
        sa.Column("axis", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_robot_joints_id"), "robot_joints", ["id"], unique=False)
    op.create_table(
        "knowledge_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("file_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("size", sa.INTEGER(), nullable=True),
        sa.Column("upload_date", sa.DATETIME(), nullable=True),
        sa.Column("tags", sa.TEXT(), nullable=True),
        sa.Column("uploaded_by", sa.INTEGER(), nullable=False),
        sa.Column("access_count", sa.INTEGER(), nullable=True),
        sa.Column("last_accessed", sa.DATETIME(), nullable=True),
        sa.Column("meta_data", sa.TEXT(), nullable=True),
        sa.Column("embedding", sa.TEXT(), nullable=True),
        sa.Column("is_public", sa.BOOLEAN(), nullable=True),
        sa.Column("checksum", sa.VARCHAR(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_items_id"), "knowledge_items", ["id"], unique=False
    )
    op.create_table(
        "robot_sensors",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("robot_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("sensor_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("model", sa.VARCHAR(length=100), nullable=True),
        sa.Column("manufacturer", sa.VARCHAR(length=100), nullable=True),
        sa.Column("sampling_rate", sa.FLOAT(), nullable=True),
        sa.Column("accuracy", sa.FLOAT(), nullable=True),
        sa.Column("range_min", sa.FLOAT(), nullable=True),
        sa.Column("range_max", sa.FLOAT(), nullable=True),
        sa.Column("position_x", sa.FLOAT(), nullable=True),
        sa.Column("position_y", sa.FLOAT(), nullable=True),
        sa.Column("position_z", sa.FLOAT(), nullable=True),
        sa.Column("orientation_x", sa.FLOAT(), nullable=True),
        sa.Column("orientation_y", sa.FLOAT(), nullable=True),
        sa.Column("orientation_z", sa.FLOAT(), nullable=True),
        sa.Column("orientation_w", sa.FLOAT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), nullable=True),
        sa.Column("last_data", sqlite.JSON(), nullable=True),
        sa.Column("last_update", sa.DATETIME(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("calibration_data", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_robot_sensors_id"), "robot_sensors", ["id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=True),
        sa.Column("model_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("message_count", sa.INTEGER(), nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), nullable=True),
        sa.Column("last_message_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_id"), "chat_sessions", ["id"], unique=False)
    op.create_table(
        "robots",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("robot_type", sa.VARCHAR(length=16), nullable=False),
        sa.Column("model", sa.VARCHAR(length=255), nullable=True),
        sa.Column("manufacturer", sa.VARCHAR(length=255), nullable=True),
        sa.Column("status", sa.VARCHAR(length=11), nullable=False),
        sa.Column("last_seen", sa.DATETIME(), nullable=True),
        sa.Column("battery_level", sa.FLOAT(), nullable=True),
        sa.Column("cpu_temperature", sa.FLOAT(), nullable=True),
        sa.Column("connection_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("connection_params", sqlite.JSON(), nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("port", sa.INTEGER(), nullable=True),
        sa.Column("configuration", sqlite.JSON(), nullable=True),
        sa.Column("urdf_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("simulation_engine", sa.VARCHAR(length=50), nullable=True),
        sa.Column("control_mode", sa.VARCHAR(length=10), nullable=True),
        sa.Column("capabilities", sqlite.JSON(), nullable=True),
        sa.Column("joint_count", sa.INTEGER(), nullable=True),
        sa.Column("sensor_count", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("is_public", sa.BOOLEAN(), nullable=True),
        sa.Column("is_default", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_robots_id"), "robots", ["id"], unique=False)
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("token", sa.VARCHAR(length=100), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("verified_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_verification_tokens_token"),
        "email_verification_tokens",
        ["token"],
        unique=1,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_id"),
        "email_verification_tokens",
        ["id"],
        unique=False,
    )
    op.create_table(
        "demonstration_tasks",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("task_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("config", sqlite.JSON(), nullable=True),
        sa.Column("success_criteria", sqlite.JSON(), nullable=True),
        sa.Column("robot_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_demonstration_tasks_id"), "demonstration_tasks", ["id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("session_token", sa.VARCHAR(length=200), nullable=False),
        sa.Column("device_info", sa.TEXT(), nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=50), nullable=True),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_table(
        "email_2fa_codes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("used", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_2fa_codes_id"), "email_2fa_codes", ["id"], unique=False
    )
    op.create_table(
        "robot_market_ratings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("listing_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("rating", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column("ease_of_use", sa.INTEGER(), nullable=True),
        sa.Column("documentation_quality", sa.INTEGER(), nullable=True),
        sa.Column("performance", sa.INTEGER(), nullable=True),
        sa.Column("reliability", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["robot_market_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id", "user_id", name=op.f("unique_rating_per_user")
        ),
    )
    op.create_index(
        op.f("ix_robot_market_ratings_id"), "robot_market_ratings", ["id"], unique=False
    )
    op.create_table(
        "demonstrations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("demonstration_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("format_type", sa.VARCHAR(length=17), nullable=True),
        sa.Column("robot_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=10), nullable=True),
        sa.Column("progress", sa.FLOAT(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("recording_duration", sa.FLOAT(), nullable=True),
        sa.Column("frame_count", sa.INTEGER(), nullable=True),
        sa.Column("data_size", sa.INTEGER(), nullable=True),
        sa.Column("sampling_rate", sa.FLOAT(), nullable=True),
        sa.Column("tags", sqlite.JSON(), nullable=True),
        sa.Column("config", sqlite.JSON(), nullable=True),
        sa.Column("sensor_config", sqlite.JSON(), nullable=True),
        sa.Column("joint_config", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("recorded_at", sa.DATETIME(), nullable=True),
        sa.Column("processed_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_demonstrations_id"), "demonstrations", ["id"], unique=False
    )
    op.create_table(
        "agi_models",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("model_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("model_path", sa.VARCHAR(length=200), nullable=True),
        sa.Column("config", sa.TEXT(), nullable=True),
        sa.Column("version", sa.VARCHAR(length=20), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_agi_models_id"), "agi_models", ["id"], unique=False)
    op.create_table(
        "robot_market_downloads",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("listing_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("download_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("file_size", sa.INTEGER(), nullable=True),
        sa.Column("download_success", sa.BOOLEAN(), nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=500), nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["robot_market_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_robot_market_downloads_id"),
        "robot_market_downloads",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_downloads_listing_user"),
        "robot_market_downloads",
        ["listing_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_downloads_created_at"),
        "robot_market_downloads",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "twofa_temp_sessions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("username_or_email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("temp_token", sa.VARCHAR(length=100), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_twofa_temp_sessions_temp_token"),
        "twofa_temp_sessions",
        ["temp_token"],
        unique=1,
    )
    op.create_index(
        op.f("ix_twofa_temp_sessions_id"), "twofa_temp_sessions", ["id"], unique=False
    )
    op.create_table(
        "training_results",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("demonstration_id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=True),
        sa.Column("training_method", sa.VARCHAR(length=50), nullable=False),
        sa.Column("training_duration", sa.FLOAT(), nullable=True),
        sa.Column("training_iterations", sa.INTEGER(), nullable=True),
        sa.Column("metrics", sqlite.JSON(), nullable=True),
        sa.Column("loss_history", sqlite.JSON(), nullable=True),
        sa.Column("accuracy_history", sqlite.JSON(), nullable=True),
        sa.Column("model_weights", sa.BLOB(), nullable=True),
        sa.Column("model_config", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["demonstration_id"],
            ["demonstrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["agi_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_results_id"), "training_results", ["id"], unique=False
    )
    op.create_table(
        "memory_associations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("source_memory_id", sa.INTEGER(), nullable=False),
        sa.Column("target_memory_id", sa.INTEGER(), nullable=False),
        sa.Column("association_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("strength", sa.FLOAT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_memory_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_memory_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_associations_id"), "memory_associations", ["id"], unique=False
    )
    op.create_table(
        "knowledge_search_history",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("query", sa.TEXT(), nullable=False),
        sa.Column("filters", sa.TEXT(), nullable=True),
        sa.Column("results_count", sa.INTEGER(), nullable=True),
        sa.Column("search_time", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_search_history_id"),
        "knowledge_search_history",
        ["id"],
        unique=False,
    )
    op.create_table(
        "demonstration_frames",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("demonstration_id", sa.INTEGER(), nullable=False),
        sa.Column("frame_index", sa.INTEGER(), nullable=False),
        sa.Column("timestamp", sa.FLOAT(), nullable=False),
        sa.Column("relative_time", sa.FLOAT(), nullable=True),
        sa.Column("joint_positions", sqlite.JSON(), nullable=True),
        sa.Column("joint_velocities", sqlite.JSON(), nullable=True),
        sa.Column("joint_torques", sqlite.JSON(), nullable=True),
        sa.Column("control_commands", sqlite.JSON(), nullable=True),
        sa.Column("target_positions", sqlite.JSON(), nullable=True),
        sa.Column("target_velocities", sqlite.JSON(), nullable=True),
        sa.Column("sensor_data", sqlite.JSON(), nullable=True),
        sa.Column("imu_data", sqlite.JSON(), nullable=True),
        sa.Column("camera_data_ref", sa.INTEGER(), nullable=True),
        sa.Column("environment_state", sqlite.JSON(), nullable=True),
        sa.Column("robot_state", sqlite.JSON(), nullable=True),
        sa.Column("frame_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("compression_ratio", sa.FLOAT(), nullable=True),
        sa.Column("data_quality", sa.FLOAT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_data_ref"],
            ["camera_frames.id"],
        ),
        sa.ForeignKeyConstraint(
            ["demonstration_id"],
            ["demonstrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_demonstration_frames_id"), "demonstration_frames", ["id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=50), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=200), nullable=False),
        sa.Column("full_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_admin", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("last_login", sa.DATETIME(), nullable=True),
        sa.Column(
            "two_factor_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("(FALSE)"),
            nullable=True,
        ),
        sa.Column(
            "two_factor_method",
            sa.VARCHAR(length=20),
            server_default=sa.text("'email'"),
            nullable=True,
        ),
        sa.Column("totp_secret", sa.VARCHAR(length=32), nullable=True),
        sa.Column("backup_codes", sa.TEXT(), nullable=True),
        sa.Column(
            "role",
            sa.VARCHAR(length=20),
            server_default=sa.text("'user'"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=1)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=1)
    op.create_table(
        "payments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("amount", sa.FLOAT(), nullable=False),
        sa.Column("currency", sa.VARCHAR(length=10), nullable=True),
        sa.Column("payment_method", sa.VARCHAR(length=20), nullable=True),
        sa.Column("transaction_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("completed_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_table(
        "camera_frames",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("demonstration_id", sa.INTEGER(), nullable=False),
        sa.Column("image_data", sa.BLOB(), nullable=True),
        sa.Column("image_format", sa.VARCHAR(length=20), nullable=True),
        sa.Column("image_width", sa.INTEGER(), nullable=True),
        sa.Column("image_height", sa.INTEGER(), nullable=True),
        sa.Column("image_channels", sa.INTEGER(), nullable=True),
        sa.Column("depth_data", sa.BLOB(), nullable=True),
        sa.Column("depth_format", sa.VARCHAR(length=20), nullable=True),
        sa.Column("depth_scale", sa.FLOAT(), nullable=True),
        sa.Column("timestamp", sa.FLOAT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["demonstration_id"],
            ["demonstrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_camera_frames_id"), "camera_frames", ["id"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("token", sa.VARCHAR(length=100), nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("used_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"),
        "password_reset_tokens",
        ["token"],
        unique=1,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_id"),
        "password_reset_tokens",
        ["id"],
        unique=False,
    )
    op.create_table(
        "robot_market_listings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("robot_id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("category", sa.VARCHAR(length=11), nullable=False),
        sa.Column("tags", sqlite.JSON(), nullable=True),
        sa.Column("version", sa.VARCHAR(length=50), nullable=True),
        sa.Column("changelog", sa.TEXT(), nullable=True),
        sa.Column("compatible_versions", sqlite.JSON(), nullable=True),
        sa.Column("config_file_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("urdf_file_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("preview_image_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("documentation_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("license_type", sa.VARCHAR(length=100), nullable=True),
        sa.Column("license_text", sa.TEXT(), nullable=True),
        sa.Column("download_count", sa.INTEGER(), nullable=True),
        sa.Column("view_count", sa.INTEGER(), nullable=True),
        sa.Column("rating_count", sa.INTEGER(), nullable=True),
        sa.Column("average_rating", sa.FLOAT(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=8), nullable=False),
        sa.Column("is_featured", sa.BOOLEAN(), nullable=True),
        sa.Column("is_verified", sa.BOOLEAN(), nullable=True),
        sa.Column("owner_id", sa.INTEGER(), nullable=False),
        sa.Column("reviewer_id", sa.INTEGER(), nullable=True),
        sa.Column("review_notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("reviewed_at", sa.DATETIME(), nullable=True),
        sa.Column("published_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_robot_market_listings_id"),
        "robot_market_listings",
        ["id"],
        unique=False,
    )
    op.create_table(
        "task_demonstrations",
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column("demonstration_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["demonstration_id"],
            ["demonstrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["demonstration_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "demonstration_id"),
    )
    op.create_table(
        "robot_market_favorites",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("listing_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("folder", sa.VARCHAR(length=100), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["robot_market_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "listing_id", "user_id", name=op.f("unique_favorite_per_user")
        ),
    )
    op.create_index(
        op.f("ix_robot_market_favorites_id"),
        "robot_market_favorites",
        ["id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("session_id", sa.INTEGER(), nullable=False),
        sa.Column("role", sa.VARCHAR(length=20), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("tokens", sa.INTEGER(), nullable=True),
        sa.Column("message_metadata", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_table(
        "robot_market_comments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("listing_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("parent_comment_id", sa.INTEGER(), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("is_question", sa.BOOLEAN(), nullable=True),
        sa.Column("is_answer", sa.BOOLEAN(), nullable=True),
        sa.Column("is_helpful", sa.BOOLEAN(), nullable=True),
        sa.Column("is_approved", sa.BOOLEAN(), nullable=True),
        sa.Column("is_edited", sa.BOOLEAN(), nullable=True),
        sa.Column("helpful_count", sa.INTEGER(), nullable=True),
        sa.Column("reply_count", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("edited_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["robot_market_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_comment_id"],
            ["robot_market_comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_robot_market_comments_id"),
        "robot_market_comments",
        ["id"],
        unique=False,
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username_or_email", sa.VARCHAR(length=100), nullable=False),
        sa.Column("attempt_count", sa.INTEGER(), nullable=False),
        sa.Column("locked_until", sa.DATETIME(), nullable=True),
        sa.Column("last_attempt_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_attempts_username_or_email"),
        "login_attempts",
        ["username_or_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_attempts_id"), "login_attempts", ["id"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("key", sa.VARCHAR(length=100), nullable=False),
        sa.Column("prefix", sa.VARCHAR(length=10), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("rate_limit", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("expires_at", sa.DATETIME(), nullable=True),
        sa.Column("last_used", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key"), "api_keys", ["key"], unique=1)
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_table(
        "memories",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("embedding", sa.TEXT(), nullable=True),
        sa.Column("importance", sa.FLOAT(), nullable=True),
        sa.Column("memory_type", sa.VARCHAR(length=20), nullable=True),
        sa.Column("accessed_count", sa.INTEGER(), nullable=True),
        sa.Column("last_accessed", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("expires_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memories_id"), "memories", ["id"], unique=False)
    # ### end Alembic commands ###
